export type UnitType = 'weight' | 'count'

export type ProductConfig = {
  unitType:            UnitType
  unitLabel:           string   // 'kg', 'each', 'punnet (500g)', etc.
  typicalBoxCount:     number   // units in a typical stall box (kg for weight items)
  maxPayPerUnitPence:  number   // max per kg or per piece
  retailUnitsPerBox?:  number   // for weight items sold per piece — estimated pieces per box
  rareBuy?:            true     // hide by default; user adds from picker
  tip?:                string
  preferredSupplier?:  'dole' | 'holland'
}

export const CONFIG: Record<string, ProductConfig> = {
  // ── VEGETABLES ────────────────────────────────────────────────────────────
  //                                                                                                                              ~pieces/box
  'Aubergine':        { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 140,                         preferredSupplier: 'holland', tip: 'Price has been falling — buy more if under £6.50/box' },
  'Butternut Squash': { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10,   maxPayPerUnitPence: 100, retailUnitsPerBox: 12,  rareBuy: true, preferredSupplier: 'dole',    tip: 'June is the start of UK season so prices are low — good time to buy extra' },
  'Cabbage White':    { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 25,   maxPayPerUnitPence:  40, retailUnitsPerBox: 14,  preferredSupplier: 'holland', tip: 'Never sell below £1.49 each — anything lower means you are losing money' },
  'Carrot Loose':     { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10,   maxPayPerUnitPence: 100,                         preferredSupplier: 'dole',    tip: 'UK-grown carrots are better quality than Chinese ones — both suppliers are fine' },
  'Celeriac':         { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 6,  maxPayPerUnitPence: 133,                         rareBuy: true, preferredSupplier: 'holland', tip: 'Great profit — about 67p profit for every £1 you make. Buy if they have it' },
  'Celery':           { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 16, maxPayPerUnitPence:  69,                         preferredSupplier: 'holland', tip: 'Good profit — you make about 50p for every £1 you sell' },
  'Chinese Leaves':   { unitType: 'count',  unitLabel: 'head', typicalBoxCount: 8,  maxPayPerUnitPence: 138,                         rareBuy: true, preferredSupplier: 'dole',    tip: 'UK-grown ones are the freshest — you make about 40p profit for every £1 you sell' },
  'Courgette':        { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 180,                         preferredSupplier: 'holland', tip: 'Only buy if the price is under £7.50/box — above that your profit gets too thin' },
  'Cucumber':         { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 14, maxPayPerUnitPence:  64,                         preferredSupplier: 'holland', tip: 'JR Holland is usually cheaper (around 51p each vs Dole at 60p+) — check their price first' },
  'Garlic Loose':     { unitType: 'count',  unitLabel: 'string', typicalBoxCount: 1, maxPayPerUnitPence: 400,                        rareBuy: true, preferredSupplier: 'holland', tip: 'Buy the whole string and split it into individual bulbs to sell — better profit than buying bulbs already split' },
  'Leek':             { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 200, retailUnitsPerBox: 25,  preferredSupplier: 'holland', tip: 'Good profit when you sell at £3.20 each — check JR Holland\'s price' },
  'Lettuce Cos':      { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 10, maxPayPerUnitPence:  90,                         preferredSupplier: 'holland', tip: 'Good profit when you pay around 80p per head — check the price is near that today' },
  'Lettuce Iceberg':  { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 10, maxPayPerUnitPence:  80,                         preferredSupplier: 'holland', tip: 'Think about raising your selling price to £1.29 — you would make more money' },
  'Mushroom Button':  { unitType: 'count',  unitLabel: 'punnet (250g)', typicalBoxCount: 12, maxPayPerUnitPence: 74, preferredSupplier: 'holland', tip: 'Holland\'s 12-pack of 250g punnets — max £8.80/box (74p/punnet). Loose 2.27kg box: use Mushroom Regular' },
  'Mushroom Regular': { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 2.27, maxPayPerUnitPence: 264,                         preferredSupplier: 'dole',    tip: 'Price has stayed at £5.20 for 3 years — very reliable, buy as normal' },
  'Onion Regular':    { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 20,   maxPayPerUnitPence:  90,                         preferredSupplier: 'dole',    tip: 'Dole\'s 20kg box of Spanish onions is the cheapest option per kg' },
  'Parsnip':          { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 140, retailUnitsPerBox: 30,  rareBuy: true, preferredSupplier: 'dole',    tip: '⚡ Lowest price ever at £1/kg — buy 2 boxes while it lasts' },
  'Pea':              { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 3,    maxPayPerUnitPence: 533,                         rareBuy: true, preferredSupplier: 'dole',    tip: 'Profit is very tight at £14/box — do not pay more than that or you will lose money' },
  'Pepper (Red)':     { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 220, retailUnitsPerBox: 30,  preferredSupplier: 'holland', tip: 'JR Holland has been cheaper than Dole recently — check their price first' },
  'Pepper (Yellow)':  { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 200, retailUnitsPerBox: 30,  preferredSupplier: 'holland', tip: 'JR Holland has been cheaper than Dole recently — check their price first' },
  'Potato':           { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10,   maxPayPerUnitPence:  80,                         preferredSupplier: 'dole',    tip: 'Reliable seller — you make about 46p profit for every £1 you sell' },
  'Potato Loose':     { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 25,   maxPayPerUnitPence:  36,                         preferredSupplier: 'dole',    tip: 'Sell at £1.20/kg — that keeps your profit margin healthy' },
  'Radish':           { unitType: 'count',  unitLabel: 'pack', typicalBoxCount: 20, maxPayPerUnitPence:  45,                         rareBuy: true, preferredSupplier: 'holland', tip: 'Low volume item — just pick up a pack if they have it, no need to buy more' },
  'Salad Cress':      { unitType: 'count',  unitLabel: 'punnet', typicalBoxCount: 16, maxPayPerUnitPence: 25,                        preferredSupplier: 'holland', tip: 'Great profit — you make about 60p for every £1 you sell. Always buy some' },
  'Shallot':          { unitType: 'count',  unitLabel: 'pack', typicalBoxCount: 20, maxPayPerUnitPence:  25,                         rareBuy: true, preferredSupplier: 'dole',    tip: 'Excellent profit — you make about 88p for every £1 you sell' },
  'Spring Onion':     { unitType: 'count',  unitLabel: 'bunch', typicalBoxCount: 12, maxPayPerUnitPence: 38,                         preferredSupplier: 'holland', tip: 'Costs about 25p a bunch and sells at 89p — easy extra profit, always worth picking up' },
  'Swede':            { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 6,  maxPayPerUnitPence: 100,                         rareBuy: true, preferredSupplier: 'holland', tip: 'Good profit — check what JR Holland is charging today' },
  'Sweet Potato':     { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 6,    maxPayPerUnitPence: 167, retailUnitsPerBox: 20,  rareBuy: true, preferredSupplier: 'dole',    tip: 'Very high profit — never put these on offer or reduce the price' },
  'Tomato':           { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 180,                         preferredSupplier: 'holland', tip: 'Always get vine tomatoes from JR Holland — better quality than Dole' },
  'Tomato Cherry':    { unitType: 'count',  unitLabel: 'punnet', typicalBoxCount: 9, maxPayPerUnitPence: 78,                         preferredSupplier: 'holland', tip: '⚡ Lowest price ever — you make about 58p profit for every £1 you sell. Buy extra' },
  'Tomato Cherry Vine':{ unitType: 'count', unitLabel: 'punnet', typicalBoxCount: 9, maxPayPerUnitPence: 89,                         preferredSupplier: 'holland', tip: 'JR Holland\'s 9-punnet vine format gives excellent profit — always get these from Holland' },
  'Tomato Plum':      { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 240,                         preferredSupplier: 'holland', tip: 'Good summer tomato — buy freely at this time of year' },

  // ── FRUIT ─────────────────────────────────────────────────────────────────
  //                                                                                                                                ~pieces/box
  'Apple Braeburn':         { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 12, maxPayPerUnitPence: 167, retailUnitsPerBox: 85,  preferredSupplier: 'dole',    tip: 'Reliable apple — steady profit of about 50p for every £1 you sell' },
  'Apple Golden Delicious': { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 12, maxPayPerUnitPence: 158, retailUnitsPerBox: 85,  preferredSupplier: 'dole',    tip: 'Standard seller with good profit — buy as normal' },
  'Apple Granny Smith':     { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 13, maxPayPerUnitPence: 154, retailUnitsPerBox: 85,  preferredSupplier: 'dole',    tip: 'Spanish Emporda apples are usually cheaper and just as good quality' },
  'Apple Pink Lady':        { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 4,  maxPayPerUnitPence: 200, retailUnitsPerBox: 25,  preferredSupplier: 'dole',    tip: 'Small 4kg box so it works out expensive per kg — only worth buying if under £8/box' },
  'Apple Royal Gala':       { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 12, maxPayPerUnitPence: 117, retailUnitsPerBox: 100, preferredSupplier: 'dole',    tip: 'UK-grown at £12/box is much better value than the Chilean ones at £22 — always choose UK' },
  'Apricot':                { unitType: 'count',  unitLabel: 'punnet (500g)', typicalBoxCount: 10, maxPayPerUnitPence: 120, rareBuy: true, preferredSupplier: 'dole', tip: '⚡ Price has dropped from £14 — good profit at 60p for every £1. Buy 3 to 4 boxes' },
  'Avocado':                { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 18, maxPayPerUnitPence: 83,                         preferredSupplier: 'dole',    tip: 'Never pay more than £15 for a box of 18. If you see a South African Hass mixed box under £8 — buy it' },
  'Banana':                 { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 18, maxPayPerUnitPence: 106, retailUnitsPerBox: 100, preferredSupplier: 'dole',    tip: 'Always ask for the 18kg Chiquita box — do not accept the smaller 13kg Dole box, it costs more per kg' },
  'Blueberry':              { unitType: 'count',  unitLabel: 'punnet (125g)', typicalBoxCount: 12, maxPayPerUnitPence: 125,                preferredSupplier: 'dole',    tip: 'Ask if they have the large Chilean bulk tray — if it is under £13 you make about 85p profit for every £1 you sell' },
  'Cherry':                 { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,  maxPayPerUnitPence: 700,                         rareBuy: true, preferredSupplier: 'holland', tip: 'June is cherry season — pay up to £35 for a 5kg box and sell at full price, do not discount' },
  'Medjool Date':           { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,  maxPayPerUnitPence: 640,                         rareBuy: true, preferredSupplier: 'dole',    tip: 'Great profit — about 59p for every £1. Always keep these in stock and never reduce the price' },
  'Grapes':                 { unitType: 'count',  unitLabel: 'punnet (500g)', typicalBoxCount: 10, maxPayPerUnitPence: 180,                preferredSupplier: 'dole',    tip: 'Never sell below £2.69 a punnet — anything less cuts your profit too much' },
  'Grapefruit':             { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 35, maxPayPerUnitPence: 57,                         rareBuy: true, preferredSupplier: 'dole',   tip: 'If you are still selling at 69p each — raise it to 89p. You will make much more money' },
  'Kiwi Loose':             { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 4,  maxPayPerUnitPence: 250, retailUnitsPerBox: 50,  rareBuy: true, preferredSupplier: 'dole',    tip: '⚠️ Price has spiked — do not buy if the 4kg box is over £10. Wait for it to come back down' },
  'Lemon':                  { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,  maxPayPerUnitPence: 200, retailUnitsPerBox: 60,  preferredSupplier: 'dole',    tip: 'Only buy Spanish lemons — never buy South African ones, the quality is not as good' },
  'Lime':                   { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 42, maxPayPerUnitPence: 19,                         preferredSupplier: 'dole',    tip: 'Good profit at 61p for every £1 — never let yourself run out of limes' },
  'Mango':                  { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 7,  maxPayPerUnitPence: 86,                         preferredSupplier: 'dole',    tip: '⚡ Price is still very low — buy 3 to 4 boxes while it lasts' },
  'Melon Cantaloupe':       { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 5,  maxPayPerUnitPence: 160, rareBuy: true,          preferredSupplier: 'dole',    tip: 'Good profit — about 40p for every £1 you sell. Buy freely' },
  'Melon Galia':            { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 6,  maxPayPerUnitPence: 150, rareBuy: true,          preferredSupplier: 'dole',    tip: 'Good melon for June — ask what price they have today before deciding' },
  'Melon Honeydew':         { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 6,  maxPayPerUnitPence: 150, rareBuy: true,          preferredSupplier: 'dole',    tip: '⚠️ Never buy the large Brazilian 7kg or 15kg boxes — only buy the small Spanish format' },
  'Melon Piel de Sapo':     { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 9,  maxPayPerUnitPence: 200, rareBuy: true,          preferredSupplier: 'dole',    tip: 'Profit is thin — make sure you sell at £2.99 each, not £2.50, otherwise you barely make anything' },
  'Watermelon':             { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 9,  maxPayPerUnitPence: 244,                         preferredSupplier: 'dole',    tip: '⚡ Lowest price ever at £2.33 per watermelon — buy more than usual while it is this cheap' },
  'Nectarine':              { unitType: 'count',  unitLabel: 'punnet (500g)', typicalBoxCount: 10, maxPayPerUnitPence: 160, rareBuy: true,  preferredSupplier: 'dole',    tip: '⚡ Price has dropped from £14–18 — buy the 10kg box as it works out cheaper per kg' },
  'Oranges Large':          { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 48, maxPayPerUnitPence: 46,                          preferredSupplier: 'dole',    tip: 'Ask if they have Moroccan oranges at £14/box — that is good value if available' },
  'Papaya':                 { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 4,  maxPayPerUnitPence: 250, rareBuy: true,          preferredSupplier: 'dole',    tip: 'Good profit at 40p for every £1 — ask Dole if they have any in today' },
  'Passion Fruit':          { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 2,  maxPayPerUnitPence: 500, retailUnitsPerBox: 40,  rareBuy: true, preferredSupplier: 'dole',    tip: '⚠️ Do not buy if the 2kg box is over £10 — you will not make enough profit' },
  'Peach':                  { unitType: 'count',  unitLabel: 'punnet (500g)', typicalBoxCount: 10, maxPayPerUnitPence: 160, rareBuy: true,  preferredSupplier: 'dole',    tip: '⚡ Price has dropped to £1.50/kg — ask for the prepacked Distinet brand first, it is the best option' },
  'Pear Conference':        { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 12, maxPayPerUnitPence: 167, retailUnitsPerBox: 66,  rareBuy: true, preferredSupplier: 'dole',    tip: 'Ask for the Dutch 10×1kg bags first — they are better value than the Belgian pears' },
  'Pear Forelle':           { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10, maxPayPerUnitPence: 190, retailUnitsPerBox: 83,  rareBuy: true, preferredSupplier: 'dole',    tip: 'Red-speckled South African pear — eye-catching, put them at the front of the display' },
  'Pineapple':              { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 8,  maxPayPerUnitPence: 175,                         preferredSupplier: 'dole',    tip: 'Profit is thin — do not pay more than £14/box or you will not make enough money' },
  'Plums Loose':            { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,  maxPayPerUnitPence: 240, retailUnitsPerBox: 100, rareBuy: true, preferredSupplier: 'dole',    tip: 'Red Beauty plums must be sold at £2.99 per 500g — do not drop to £1.99 or you lose money' },
  'Pomegranate':            { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 8,  maxPayPerUnitPence: 125, rareBuy: true,          preferredSupplier: 'dole',    tip: '⚡ Price has dropped from £10 — never sell below £1.89 each' },
  'Satsuma':                { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10, maxPayPerUnitPence: 180,                        rareBuy: true, preferredSupplier: 'dole',    tip: 'Unusual to have these in June — tell customers they are a special seasonal find to help sell them' },
  'Starfruit':              { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 10, maxPayPerUnitPence: 120, rareBuy: true,          preferredSupplier: 'dole',    tip: 'Only buy if the box is under £12 — never sell below £2.50 each or you lose money' },
  'Strawberry':             { unitType: 'count',  unitLabel: 'punnet (500g)', typicalBoxCount: 8, maxPayPerUnitPence: 275,                  preferredSupplier: 'dole',    tip: '⚡ Belgian strawberry price has dropped a lot — keep selling at £4.99 and do NOT put them on offer' },
}
