export type UnitType = 'weight' | 'count'

export type ProductConfig = {
  unitType:            UnitType
  unitLabel:           string   // 'kg', 'each', 'punnet (500g)', etc.
  typicalBoxCount:     number   // units in a typical stall box (kg for weight items)
  maxPayPerUnitPence:  number   // max per kg or per piece
  retailUnitsPerBox?:  number   // for weight items sold per piece — estimated pieces per box
  rareBuy?:            true     // hide by default; user adds from picker
  preferredSupplier?:  'dole' | 'holland'
}

export const CONFIG: Record<string, ProductConfig> = {
  // ── VEGETABLES ────────────────────────────────────────────────────────────
  //                                                                                                                              ~pieces/box
  'Aubergine':        { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 140,                         preferredSupplier: 'holland' },
  'Butternut Squash': { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10,   maxPayPerUnitPence: 100, retailUnitsPerBox: 12,  rareBuy: true, preferredSupplier: 'dole'    },
  'Cabbage White':    { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 25,   maxPayPerUnitPence:  40, retailUnitsPerBox: 14,  preferredSupplier: 'holland' },
  'Carrot Loose':     { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10,   maxPayPerUnitPence: 100,                         preferredSupplier: 'dole'    },
  'Celeriac':         { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 6,  maxPayPerUnitPence: 133,                         rareBuy: true, preferredSupplier: 'holland' },
  'Celery':           { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 16, maxPayPerUnitPence:  69,                         preferredSupplier: 'holland' },
  'Chinese Leaves':   { unitType: 'count',  unitLabel: 'head', typicalBoxCount: 8,  maxPayPerUnitPence: 138,                         rareBuy: true, preferredSupplier: 'dole'    },
  'Courgette':        { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 180,                         preferredSupplier: 'holland' },
  'Cucumber':         { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 14, maxPayPerUnitPence:  64,                         preferredSupplier: 'holland' },
  'Garlic Loose':     { unitType: 'count',  unitLabel: 'string', typicalBoxCount: 1, maxPayPerUnitPence: 400,                        rareBuy: true, preferredSupplier: 'holland' },
  'Leek':             { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 260, retailUnitsPerBox: 25,  preferredSupplier: 'holland' },
  'Lettuce Cos':      { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 10, maxPayPerUnitPence:  90,                         preferredSupplier: 'holland' },
  'Lettuce Iceberg':  { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 10, maxPayPerUnitPence:  80,                         preferredSupplier: 'holland' },
  'Mushroom Button':  { unitType: 'count',  unitLabel: 'punnet (250g)', typicalBoxCount: 12, maxPayPerUnitPence: 74, preferredSupplier: 'holland' },
  'Mushroom Punnet':  { unitType: 'count',  unitLabel: 'punnet', typicalBoxCount: 6,  maxPayPerUnitPence: 120,                         preferredSupplier: 'holland' },
  'Mushroom Regular': { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 2.27, maxPayPerUnitPence: 264,                         preferredSupplier: 'dole'    },
  'Onion Regular':    { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 20,   maxPayPerUnitPence:  90,                         preferredSupplier: 'dole'    },
  'Parsnip':          { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 140, retailUnitsPerBox: 30,  rareBuy: true, preferredSupplier: 'dole'    },
  'Pea':              { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 3,    maxPayPerUnitPence: 533,                         rareBuy: true, preferredSupplier: 'dole'    },
  'Pepper (Red)':     { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 220, retailUnitsPerBox: 30,  preferredSupplier: 'holland' },
  'Pepper (Yellow)':  { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 200, retailUnitsPerBox: 30,  preferredSupplier: 'holland' },
  'Potato':           { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10,   maxPayPerUnitPence:  80,                         preferredSupplier: 'dole'    },
  'Potato Loose':     { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 25,   maxPayPerUnitPence:  36,                         preferredSupplier: 'dole'    },
  'Radish':           { unitType: 'count',  unitLabel: 'pack', typicalBoxCount: 20, maxPayPerUnitPence:  45,                         rareBuy: true, preferredSupplier: 'holland' },
  'Salad Cress':      { unitType: 'count',  unitLabel: 'punnet', typicalBoxCount: 16, maxPayPerUnitPence: 25,                        preferredSupplier: 'holland' },
  'Shallot':          { unitType: 'count',  unitLabel: 'pack', typicalBoxCount: 20, maxPayPerUnitPence:  25,                         rareBuy: true, preferredSupplier: 'dole'    },
  'Spring Onion':     { unitType: 'count',  unitLabel: 'bunch', typicalBoxCount: 12, maxPayPerUnitPence: 38,                         preferredSupplier: 'holland' },
  'Swede':            { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 6,  maxPayPerUnitPence: 100,                         rareBuy: true, preferredSupplier: 'holland' },
  'Sweet Potato':     { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 6,    maxPayPerUnitPence: 167, retailUnitsPerBox: 20,  rareBuy: true, preferredSupplier: 'dole'    },
  'Tomato':           { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 180,                         preferredSupplier: 'holland' },
  'Tomato Cherry':    { unitType: 'count',  unitLabel: 'punnet', typicalBoxCount: 9, maxPayPerUnitPence: 78,                         preferredSupplier: 'holland' },
  'Tomato Cherry Vine':{ unitType: 'count', unitLabel: 'punnet', typicalBoxCount: 9, maxPayPerUnitPence: 89,                         preferredSupplier: 'holland' },
  'Tomato Plum':      { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,    maxPayPerUnitPence: 240,                         preferredSupplier: 'holland' },
  'Bean Fine':        { unitType: 'count',  unitLabel: 'bag', typicalBoxCount: 15, maxPayPerUnitPence: 100,                         preferredSupplier: 'holland' },
  'Beetroot':         { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10,  maxPayPerUnitPence:  80,                         rareBuy: true, preferredSupplier: 'holland' },
  'Broccoli':         { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,   maxPayPerUnitPence: 120,                         preferredSupplier: 'holland' },
  'Cauliflower':      { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 8, maxPayPerUnitPence:  80,                         preferredSupplier: 'holland' },
  'Kohlrabi':         { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 10, maxPayPerUnitPence: 200,                        rareBuy: true, preferredSupplier: 'holland' },
  'Onion Red':        { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10,  maxPayPerUnitPence:  70,                         preferredSupplier: 'holland' },
  'Onion Spanish':    { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10,  maxPayPerUnitPence:  60,                         rareBuy: true, preferredSupplier: 'dole'    },
  'Pepper (Mixed)':   { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,   maxPayPerUnitPence: 300,                         preferredSupplier: 'holland' },
  'Red Cabbage':      { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10,  maxPayPerUnitPence:  80,                         preferredSupplier: 'holland' },
  'Spinach':          { unitType: 'count',  unitLabel: 'bag', typicalBoxCount: 12, maxPayPerUnitPence:  60,                         rareBuy: true, preferredSupplier: 'holland' },
  'Sugarsnap':        { unitType: 'count',  unitLabel: 'bag', typicalBoxCount: 8,  maxPayPerUnitPence: 140,                         rareBuy: true, preferredSupplier: 'holland' },

  // ── FRUIT ─────────────────────────────────────────────────────────────────
  //                                                                                                                                ~pieces/box
  'Apple Braeburn':         { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 12, maxPayPerUnitPence: 167, retailUnitsPerBox: 85,  preferredSupplier: 'dole'    },
  'Apple Golden Delicious': { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 12, maxPayPerUnitPence: 158, retailUnitsPerBox: 85,  preferredSupplier: 'dole'    },
  'Apple Granny Smith':     { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 13, maxPayPerUnitPence: 154, retailUnitsPerBox: 85,  preferredSupplier: 'dole'    },
  'Apple Pink Lady':        { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 4,  maxPayPerUnitPence: 225, retailUnitsPerBox: 25,  preferredSupplier: 'dole'    },
  'Apple Royal Gala':       { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 12, maxPayPerUnitPence: 200, retailUnitsPerBox: 100, preferredSupplier: 'dole'    },
  'Apricot':                { unitType: 'count',  unitLabel: 'punnet (500g)', typicalBoxCount: 10, maxPayPerUnitPence: 120, rareBuy: true, preferredSupplier: 'dole' },
  'Avocado':                { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 18, maxPayPerUnitPence: 83,                         preferredSupplier: 'dole'    },
  'Banana':                 { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 18, maxPayPerUnitPence: 106, retailUnitsPerBox: 100, preferredSupplier: 'dole'    },
  'Blueberry':              { unitType: 'count',  unitLabel: 'punnet (125g)', typicalBoxCount: 12, maxPayPerUnitPence: 125,                preferredSupplier: 'dole'    },
  'Cherry':                 { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,  maxPayPerUnitPence: 700,                         rareBuy: true, preferredSupplier: 'holland' },
  'Medjool Date':           { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,  maxPayPerUnitPence: 640,                         rareBuy: true, preferredSupplier: 'dole'    },
  'Grapes':                 { unitType: 'count',  unitLabel: 'punnet (500g)', typicalBoxCount: 10, maxPayPerUnitPence: 180,                preferredSupplier: 'dole'    },
  'Grapefruit':             { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 35, maxPayPerUnitPence: 57,                         rareBuy: true, preferredSupplier: 'dole'   },
  'Kiwi Loose':             { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 4,  maxPayPerUnitPence: 250, retailUnitsPerBox: 50,  rareBuy: true, preferredSupplier: 'dole'    },
  'Lemon':                  { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,  maxPayPerUnitPence: 200, retailUnitsPerBox: 60,  preferredSupplier: 'dole'    },
  'Lime':                   { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 42, maxPayPerUnitPence: 19,                         preferredSupplier: 'dole'    },
  'Mango':                  { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 7,  maxPayPerUnitPence: 86,                         preferredSupplier: 'dole'    },
  'Melon Cantaloupe':       { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 5,  maxPayPerUnitPence: 160, rareBuy: true,          preferredSupplier: 'dole'    },
  'Melon Galia':            { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 6,  maxPayPerUnitPence: 150, rareBuy: true,          preferredSupplier: 'dole'    },
  'Melon Honeydew':         { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 6,  maxPayPerUnitPence: 150, rareBuy: true,          preferredSupplier: 'dole'    },
  'Melon Piel de Sapo':     { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 9,  maxPayPerUnitPence: 200, rareBuy: true,          preferredSupplier: 'dole'    },
  'Watermelon':             { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 9,  maxPayPerUnitPence: 244,                         preferredSupplier: 'dole'    },
  'Nectarine':              { unitType: 'count',  unitLabel: 'punnet (500g)', typicalBoxCount: 10, maxPayPerUnitPence: 160, rareBuy: true,  preferredSupplier: 'dole'    },
  'Oranges Large':          { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 40, maxPayPerUnitPence: 55,                          preferredSupplier: 'dole'    },
  'Papaya':                 { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 4,  maxPayPerUnitPence: 250, rareBuy: true,          preferredSupplier: 'dole'    },
  'Passion Fruit':          { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 2,  maxPayPerUnitPence: 500, retailUnitsPerBox: 40,  rareBuy: true, preferredSupplier: 'dole'    },
  'Peach':                  { unitType: 'count',  unitLabel: 'punnet (500g)', typicalBoxCount: 10, maxPayPerUnitPence: 160, rareBuy: true,  preferredSupplier: 'dole'    },
  'Pear Conference':        { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 12, maxPayPerUnitPence: 167, retailUnitsPerBox: 66,  rareBuy: true, preferredSupplier: 'dole'    },
  'Pear Forelle':           { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 10, maxPayPerUnitPence: 190, retailUnitsPerBox: 83,  rareBuy: true, preferredSupplier: 'dole'    },
  'Pineapple':              { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 8,  maxPayPerUnitPence: 175,                         preferredSupplier: 'dole'    },
  'Plums Loose':            { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 5,  maxPayPerUnitPence: 240, retailUnitsPerBox: 100, rareBuy: true, preferredSupplier: 'dole'    },
  'Pomegranate':            { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 8,  maxPayPerUnitPence: 125, rareBuy: true,          preferredSupplier: 'dole'    },
  'Tangerine':              { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 70, maxPayPerUnitPence: 25,                        rareBuy: true, preferredSupplier: 'dole'    },
  'Starfruit':              { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 10, maxPayPerUnitPence: 120, rareBuy: true,          preferredSupplier: 'dole'    },
  'Strawberry':             { unitType: 'count',  unitLabel: 'punnet (500g)', typicalBoxCount: 8, maxPayPerUnitPence: 275,                  preferredSupplier: 'dole'    },
  'Strawberry Punnet':      { unitType: 'count',  unitLabel: 'punnet (500g)', typicalBoxCount: 8, maxPayPerUnitPence: 250,                  preferredSupplier: 'dole'    },
  'Apple Bramley':          { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 12, maxPayPerUnitPence: 200, retailUnitsPerBox: 60,  rareBuy: true, preferredSupplier: 'dole'    },
  'Apple Cripps Pink':      { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 4,  maxPayPerUnitPence: 225, retailUnitsPerBox: 25,  rareBuy: true, preferredSupplier: 'dole'    },
  'Apple Red Delicious':    { unitType: 'weight', unitLabel: 'kg', typicalBoxCount: 12, maxPayPerUnitPence: 180, retailUnitsPerBox: 85,  rareBuy: true, preferredSupplier: 'dole'    },
  'Apricot Punnet':         { unitType: 'count',  unitLabel: 'punnet', typicalBoxCount: 10, maxPayPerUnitPence: 160,                     rareBuy: true, preferredSupplier: 'dole'    },
  'Nectarine Punnet':       { unitType: 'count',  unitLabel: 'punnet (250g)', typicalBoxCount: 12, maxPayPerUnitPence: 70,               rareBuy: true, preferredSupplier: 'dole'    },
  'Plums Punnet':           { unitType: 'count',  unitLabel: 'punnet', typicalBoxCount: 12, maxPayPerUnitPence: 120,                     rareBuy: true, preferredSupplier: 'dole'    },
  'Physalis':               { unitType: 'count',  unitLabel: 'punnet', typicalBoxCount: 12, maxPayPerUnitPence: 130,                      rareBuy: true, preferredSupplier: 'holland' },
  'Watermelon Large':       { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 4,  maxPayPerUnitPence: 380,                        rareBuy: true, preferredSupplier: 'dole'    },
  'Watermelon Small':       { unitType: 'count',  unitLabel: 'each', typicalBoxCount: 9,  maxPayPerUnitPence: 120,                        rareBuy: true, preferredSupplier: 'dole'    },
}
